a =['pythan','exception','try and except']
try:
    for i in range(4):
        print("The index and element from the array is", 1,a[i])

except:
    print("index out of range")